//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService.IntegrationCMDvogue {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/POSServer.External")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RestService.IntegrationCMDvogue.DiscountCard DiscountCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RestService.IntegrationCMDvogue.OrderItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RestService.IntegrationCMDvogue.OrderPayment OrderPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RestService.IntegrationCMDvogue.OrderStatus OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RestaurantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RestService.IntegrationCMDvogue.Waiter WaiterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestService.IntegrationCMDvogue.DiscountCard DiscountCard {
            get {
                return this.DiscountCardField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountCardField, value) != true)) {
                    this.DiscountCardField = value;
                    this.RaisePropertyChanged("DiscountCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestService.IntegrationCMDvogue.OrderItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestService.IntegrationCMDvogue.OrderPayment OrderPayment {
            get {
                return this.OrderPaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderPaymentField, value) != true)) {
                    this.OrderPaymentField = value;
                    this.RaisePropertyChanged("OrderPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestService.IntegrationCMDvogue.OrderStatus OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderStatusField, value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RestaurantID {
            get {
                return this.RestaurantIDField;
            }
            set {
                if ((this.RestaurantIDField.Equals(value) != true)) {
                    this.RestaurantIDField = value;
                    this.RaisePropertyChanged("RestaurantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableID {
            get {
                return this.TableIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TableIDField, value) != true)) {
                    this.TableIDField = value;
                    this.RaisePropertyChanged("TableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestService.IntegrationCMDvogue.Waiter Waiter {
            get {
                return this.WaiterField;
            }
            set {
                if ((object.ReferenceEquals(this.WaiterField, value) != true)) {
                    this.WaiterField = value;
                    this.RaisePropertyChanged("Waiter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscountCard", Namespace="http://schemas.datacontract.org/2004/07/POSServer.External")]
    [System.SerializableAttribute()]
    public partial class DiscountCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((this.CardNumberField.Equals(value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardStatus {
            get {
                return this.CardStatusField;
            }
            set {
                if ((this.CardStatusField.Equals(value) != true)) {
                    this.CardStatusField = value;
                    this.RaisePropertyChanged("CardStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastDate {
            get {
                return this.LastDateField;
            }
            set {
                if ((this.LastDateField.Equals(value) != true)) {
                    this.LastDateField = value;
                    this.RaisePropertyChanged("LastDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPayment", Namespace="http://schemas.datacontract.org/2004/07/POSServer.External")]
    [System.SerializableAttribute()]
    public partial class OrderPayment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DiscountSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OrderSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OrderTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountSum {
            get {
                return this.DiscountSumField;
            }
            set {
                if ((this.DiscountSumField.Equals(value) != true)) {
                    this.DiscountSumField = value;
                    this.RaisePropertyChanged("DiscountSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderSum {
            get {
                return this.OrderSumField;
            }
            set {
                if ((this.OrderSumField.Equals(value) != true)) {
                    this.OrderSumField = value;
                    this.RaisePropertyChanged("OrderSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderTotal {
            get {
                return this.OrderTotalField;
            }
            set {
                if ((this.OrderTotalField.Equals(value) != true)) {
                    this.OrderTotalField = value;
                    this.RaisePropertyChanged("OrderTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatus", Namespace="http://schemas.datacontract.org/2004/07/POSServer.External")]
    [System.SerializableAttribute()]
    public partial class OrderStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatusDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusDate {
            get {
                return this.StatusDateField;
            }
            set {
                if ((this.StatusDateField.Equals(value) != true)) {
                    this.StatusDateField = value;
                    this.RaisePropertyChanged("StatusDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Waiter", Namespace="http://schemas.datacontract.org/2004/07/POSServer.External")]
    [System.SerializableAttribute()]
    public partial class Waiter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItem", Namespace="http://schemas.datacontract.org/2004/07/POSServer.External")]
    [System.SerializableAttribute()]
    public partial class OrderItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntegrationCMDvogue.IIntegrationCMD")]
    public interface IIntegrationCMD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/FindOrders", ReplyAction="http://tempuri.org/IIntegrationCMD/FindOrdersResponse")]
        RestService.IntegrationCMDvogue.Order[] FindOrders(int restaurantID, int techItem, System.Nullable<long> discountCardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/FindOrders", ReplyAction="http://tempuri.org/IIntegrationCMD/FindOrdersResponse")]
        System.Threading.Tasks.Task<RestService.IntegrationCMDvogue.Order[]> FindOrdersAsync(int restaurantID, int techItem, System.Nullable<long> discountCardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/FindOrdersFull", ReplyAction="http://tempuri.org/IIntegrationCMD/FindOrdersFullResponse")]
        RestService.IntegrationCMDvogue.Order[] FindOrdersFull(int restaurantID, int techItem, System.Nullable<long> discountCardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/FindOrdersFull", ReplyAction="http://tempuri.org/IIntegrationCMD/FindOrdersFullResponse")]
        System.Threading.Tasks.Task<RestService.IntegrationCMDvogue.Order[]> FindOrdersFullAsync(int restaurantID, int techItem, System.Nullable<long> discountCardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/GetOrder", ReplyAction="http://tempuri.org/IIntegrationCMD/GetOrderResponse")]
        RestService.IntegrationCMDvogue.Order[] GetOrder(int restaurantID, string orderNumber, System.Nullable<long> discountCardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/GetOrder", ReplyAction="http://tempuri.org/IIntegrationCMD/GetOrderResponse")]
        System.Threading.Tasks.Task<RestService.IntegrationCMDvogue.Order[]> GetOrderAsync(int restaurantID, string orderNumber, System.Nullable<long> discountCardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/CallWaiter", ReplyAction="http://tempuri.org/IIntegrationCMD/CallWaiterResponse")]
        int CallWaiter(int restaurantID, string tableID, string orderNumber, int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/CallWaiter", ReplyAction="http://tempuri.org/IIntegrationCMD/CallWaiterResponse")]
        System.Threading.Tasks.Task<int> CallWaiterAsync(int restaurantID, string tableID, string orderNumber, int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/CallAdmin", ReplyAction="http://tempuri.org/IIntegrationCMD/CallAdminResponse")]
        int CallAdmin(int restaurantID, string tableID, string orderNumber, int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/CallAdmin", ReplyAction="http://tempuri.org/IIntegrationCMD/CallAdminResponse")]
        System.Threading.Tasks.Task<int> CallAdminAsync(int restaurantID, string tableID, string orderNumber, int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/OrderPrecheck", ReplyAction="http://tempuri.org/IIntegrationCMD/OrderPrecheckResponse")]
        RestService.IntegrationCMDvogue.Order[] OrderPrecheck(int restaurantID, string orderNumber, System.Nullable<long> discountCardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/OrderPrecheck", ReplyAction="http://tempuri.org/IIntegrationCMD/OrderPrecheckResponse")]
        System.Threading.Tasks.Task<RestService.IntegrationCMDvogue.Order[]> OrderPrecheckAsync(int restaurantID, string orderNumber, System.Nullable<long> discountCardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/CancelPrecheck", ReplyAction="http://tempuri.org/IIntegrationCMD/CancelPrecheckResponse")]
        RestService.IntegrationCMDvogue.Order[] CancelPrecheck(int restaurantID, string orderNumber, System.Nullable<long> discountCardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/CancelPrecheck", ReplyAction="http://tempuri.org/IIntegrationCMD/CancelPrecheckResponse")]
        System.Threading.Tasks.Task<RestService.IntegrationCMDvogue.Order[]> CancelPrecheckAsync(int restaurantID, string orderNumber, System.Nullable<long> discountCardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/GetPayment", ReplyAction="http://tempuri.org/IIntegrationCMD/GetPaymentResponse")]
        RestService.IntegrationCMDvogue.Order[] GetPayment(int restaurantID, string orderNumber, decimal paymentSum, System.DateTime paymentDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/GetPayment", ReplyAction="http://tempuri.org/IIntegrationCMD/GetPaymentResponse")]
        System.Threading.Tasks.Task<RestService.IntegrationCMDvogue.Order[]> GetPaymentAsync(int restaurantID, string orderNumber, decimal paymentSum, System.DateTime paymentDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/CheckRestaurant", ReplyAction="http://tempuri.org/IIntegrationCMD/CheckRestaurantResponse")]
        int CheckRestaurant(int restaurantID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationCMD/CheckRestaurant", ReplyAction="http://tempuri.org/IIntegrationCMD/CheckRestaurantResponse")]
        System.Threading.Tasks.Task<int> CheckRestaurantAsync(int restaurantID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegrationCMDChannel : RestService.IntegrationCMDvogue.IIntegrationCMD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegrationCMDClient : System.ServiceModel.ClientBase<RestService.IntegrationCMDvogue.IIntegrationCMD>, RestService.IntegrationCMDvogue.IIntegrationCMD {
        
        public IntegrationCMDClient() {
        }
        
        public IntegrationCMDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegrationCMDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationCMDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationCMDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RestService.IntegrationCMDvogue.Order[] FindOrders(int restaurantID, int techItem, System.Nullable<long> discountCardNumber) {
            return base.Channel.FindOrders(restaurantID, techItem, discountCardNumber);
        }
        
        public System.Threading.Tasks.Task<RestService.IntegrationCMDvogue.Order[]> FindOrdersAsync(int restaurantID, int techItem, System.Nullable<long> discountCardNumber) {
            return base.Channel.FindOrdersAsync(restaurantID, techItem, discountCardNumber);
        }
        
        public RestService.IntegrationCMDvogue.Order[] FindOrdersFull(int restaurantID, int techItem, System.Nullable<long> discountCardNumber) {
            return base.Channel.FindOrdersFull(restaurantID, techItem, discountCardNumber);
        }
        
        public System.Threading.Tasks.Task<RestService.IntegrationCMDvogue.Order[]> FindOrdersFullAsync(int restaurantID, int techItem, System.Nullable<long> discountCardNumber) {
            return base.Channel.FindOrdersFullAsync(restaurantID, techItem, discountCardNumber);
        }
        
        public RestService.IntegrationCMDvogue.Order[] GetOrder(int restaurantID, string orderNumber, System.Nullable<long> discountCardNumber) {
            return base.Channel.GetOrder(restaurantID, orderNumber, discountCardNumber);
        }
        
        public System.Threading.Tasks.Task<RestService.IntegrationCMDvogue.Order[]> GetOrderAsync(int restaurantID, string orderNumber, System.Nullable<long> discountCardNumber) {
            return base.Channel.GetOrderAsync(restaurantID, orderNumber, discountCardNumber);
        }
        
        public int CallWaiter(int restaurantID, string tableID, string orderNumber, int code) {
            return base.Channel.CallWaiter(restaurantID, tableID, orderNumber, code);
        }
        
        public System.Threading.Tasks.Task<int> CallWaiterAsync(int restaurantID, string tableID, string orderNumber, int code) {
            return base.Channel.CallWaiterAsync(restaurantID, tableID, orderNumber, code);
        }
        
        public int CallAdmin(int restaurantID, string tableID, string orderNumber, int code) {
            return base.Channel.CallAdmin(restaurantID, tableID, orderNumber, code);
        }
        
        public System.Threading.Tasks.Task<int> CallAdminAsync(int restaurantID, string tableID, string orderNumber, int code) {
            return base.Channel.CallAdminAsync(restaurantID, tableID, orderNumber, code);
        }
        
        public RestService.IntegrationCMDvogue.Order[] OrderPrecheck(int restaurantID, string orderNumber, System.Nullable<long> discountCardNumber) {
            return base.Channel.OrderPrecheck(restaurantID, orderNumber, discountCardNumber);
        }
        
        public System.Threading.Tasks.Task<RestService.IntegrationCMDvogue.Order[]> OrderPrecheckAsync(int restaurantID, string orderNumber, System.Nullable<long> discountCardNumber) {
            return base.Channel.OrderPrecheckAsync(restaurantID, orderNumber, discountCardNumber);
        }
        
        public RestService.IntegrationCMDvogue.Order[] CancelPrecheck(int restaurantID, string orderNumber, System.Nullable<long> discountCardNumber) {
            return base.Channel.CancelPrecheck(restaurantID, orderNumber, discountCardNumber);
        }
        
        public System.Threading.Tasks.Task<RestService.IntegrationCMDvogue.Order[]> CancelPrecheckAsync(int restaurantID, string orderNumber, System.Nullable<long> discountCardNumber) {
            return base.Channel.CancelPrecheckAsync(restaurantID, orderNumber, discountCardNumber);
        }
        
        public RestService.IntegrationCMDvogue.Order[] GetPayment(int restaurantID, string orderNumber, decimal paymentSum, System.DateTime paymentDate) {
            return base.Channel.GetPayment(restaurantID, orderNumber, paymentSum, paymentDate);
        }
        
        public System.Threading.Tasks.Task<RestService.IntegrationCMDvogue.Order[]> GetPaymentAsync(int restaurantID, string orderNumber, decimal paymentSum, System.DateTime paymentDate) {
            return base.Channel.GetPaymentAsync(restaurantID, orderNumber, paymentSum, paymentDate);
        }
        
        public int CheckRestaurant(int restaurantID) {
            return base.Channel.CheckRestaurant(restaurantID);
        }
        
        public System.Threading.Tasks.Task<int> CheckRestaurantAsync(int restaurantID) {
            return base.Channel.CheckRestaurantAsync(restaurantID);
        }
    }
}
