//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService.CommService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.devinosms.com", ConfigurationName="CommService.SmsServiceSoap")]
    public interface SmsServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetMessageState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntityOfInt64))]
        RestService.CommService.MessageStateInfo GetMessageState(string sessionID, string messageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetMessageState", ReplyAction="*")]
        System.Threading.Tasks.Task<RestService.CommService.MessageStateInfo> GetMessageStateAsync(string sessionID, string messageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetSessionID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntityOfInt64))]
        string GetSessionID(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetSessionID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSessionIDAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntityOfInt64))]
        string[] SendMessage(string sessionID, RestService.CommService.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> SendMessageAsync(string sessionID, RestService.CommService.Message message);
        
        // CODEGEN: Параметр "validity" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessageByTimeZone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntityOfInt64))]
        RestService.CommService.SendMessageByTimeZoneResponse SendMessageByTimeZone(RestService.CommService.SendMessageByTimeZoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessageByTimeZone", ReplyAction="*")]
        System.Threading.Tasks.Task<RestService.CommService.SendMessageByTimeZoneResponse> SendMessageByTimeZoneAsync(RestService.CommService.SendMessageByTimeZoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntityOfInt64))]
        decimal GetBalance(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> GetBalanceAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetIncomingMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntityOfInt64))]
        RestService.CommService.IncomingMessage[] GetIncomingMessages(string sessionID, System.DateTime maxDateUTC, System.DateTime minDateUTC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetIncomingMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<RestService.CommService.IncomingMessage[]> GetIncomingMessagesAsync(string sessionID, System.DateTime maxDateUTC, System.DateTime minDateUTC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetStatistics", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntityOfInt64))]
        RestService.CommService.DeliveryStatistics GetStatistics(string sessionId, System.DateTime startDateTime, System.DateTime endDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetStatistics", ReplyAction="*")]
        System.Threading.Tasks.Task<RestService.CommService.DeliveryStatistics> GetStatisticsAsync(string sessionId, System.DateTime startDateTime, System.DateTime endDateTime);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.devinosms.com")]
    public partial class MessageStateInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int stateField;
        
        private System.Nullable<System.DateTime> creationDateUtcField;
        
        private System.Nullable<System.DateTime> submittedDateUtcField;
        
        private System.Nullable<System.DateTime> reportedDateUtcField;
        
        private string stateDescriptionField;
        
        private System.Nullable<decimal> priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> CreationDateUtc {
            get {
                return this.creationDateUtcField;
            }
            set {
                this.creationDateUtcField = value;
                this.RaisePropertyChanged("CreationDateUtc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> SubmittedDateUtc {
            get {
                return this.submittedDateUtcField;
            }
            set {
                this.submittedDateUtcField = value;
                this.RaisePropertyChanged("SubmittedDateUtc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> ReportedDateUtc {
            get {
                return this.reportedDateUtcField;
            }
            set {
                this.reportedDateUtcField = value;
                this.RaisePropertyChanged("ReportedDateUtc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StateDescription {
            get {
                return this.stateDescriptionField;
            }
            set {
                this.stateDescriptionField = value;
                this.RaisePropertyChanged("StateDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.devinosms.com")]
    public partial class DeliveryStatistics : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sentField;
        
        private int deliveredField;
        
        private int errorsField;
        
        private int inProcessField;
        
        private int expiredField;
        
        private int rejectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Sent {
            get {
                return this.sentField;
            }
            set {
                this.sentField = value;
                this.RaisePropertyChanged("Sent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Delivered {
            get {
                return this.deliveredField;
            }
            set {
                this.deliveredField = value;
                this.RaisePropertyChanged("Delivered");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int InProcess {
            get {
                return this.inProcessField;
            }
            set {
                this.inProcessField = value;
                this.RaisePropertyChanged("InProcess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Expired {
            get {
                return this.expiredField;
            }
            set {
                this.expiredField = value;
                this.RaisePropertyChanged("Expired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Rejected {
            get {
                return this.rejectedField;
            }
            set {
                this.rejectedField = value;
                this.RaisePropertyChanged("Rejected");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IncomingMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.devinosms.com")]
    public abstract partial class AbstractEntityOfInt64 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.devinosms.com")]
    public partial class IncomingMessage : AbstractEntityOfInt64 {
        
        private string dataField;
        
        private string sourceAddressField;
        
        private string destinationAddressField;
        
        private System.DateTime createdDateUtcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SourceAddress {
            get {
                return this.sourceAddressField;
            }
            set {
                this.sourceAddressField = value;
                this.RaisePropertyChanged("SourceAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DestinationAddress {
            get {
                return this.destinationAddressField;
            }
            set {
                this.destinationAddressField = value;
                this.RaisePropertyChanged("DestinationAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime CreatedDateUtc {
            get {
                return this.createdDateUtcField;
            }
            set {
                this.createdDateUtcField = value;
                this.RaisePropertyChanged("CreatedDateUtc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.devinosms.com")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataField;
        
        private System.Nullable<System.DateTime> delayUntilUtcField;
        
        private string[] destinationAddressesField;
        
        private string sourceAddressField;
        
        private bool receiptRequestedField;
        
        private System.Nullable<int> validityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> DelayUntilUtc {
            get {
                return this.delayUntilUtcField;
            }
            set {
                this.delayUntilUtcField = value;
                this.RaisePropertyChanged("DelayUntilUtc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] DestinationAddresses {
            get {
                return this.destinationAddressesField;
            }
            set {
                this.destinationAddressesField = value;
                this.RaisePropertyChanged("DestinationAddresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SourceAddress {
            get {
                return this.sourceAddressField;
            }
            set {
                this.sourceAddressField = value;
                this.RaisePropertyChanged("SourceAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool ReceiptRequested {
            get {
                return this.receiptRequestedField;
            }
            set {
                this.receiptRequestedField = value;
                this.RaisePropertyChanged("ReceiptRequested");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> Validity {
            get {
                return this.validityField;
            }
            set {
                this.validityField = value;
                this.RaisePropertyChanged("Validity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageByTimeZone", WrapperNamespace="http://ws.devinosms.com", IsWrapped=true)]
    public partial class SendMessageByTimeZoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.devinosms.com", Order=0)]
        public string sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.devinosms.com", Order=1)]
        public string sourceAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.devinosms.com", Order=2)]
        public string destinationAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.devinosms.com", Order=3)]
        public string data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.devinosms.com", Order=4)]
        public System.DateTime sendDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.devinosms.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> validity;
        
        public SendMessageByTimeZoneRequest() {
        }
        
        public SendMessageByTimeZoneRequest(string sessionID, string sourceAddress, string destinationAddress, string data, System.DateTime sendDate, System.Nullable<int> validity) {
            this.sessionID = sessionID;
            this.sourceAddress = sourceAddress;
            this.destinationAddress = destinationAddress;
            this.data = data;
            this.sendDate = sendDate;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageByTimeZoneResponse", WrapperNamespace="http://ws.devinosms.com", IsWrapped=true)]
    public partial class SendMessageByTimeZoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.devinosms.com", Order=0)]
        public string[] SendMessageByTimeZoneResult;
        
        public SendMessageByTimeZoneResponse() {
        }
        
        public SendMessageByTimeZoneResponse(string[] SendMessageByTimeZoneResult) {
            this.SendMessageByTimeZoneResult = SendMessageByTimeZoneResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsServiceSoapChannel : RestService.CommService.SmsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsServiceSoapClient : System.ServiceModel.ClientBase<RestService.CommService.SmsServiceSoap>, RestService.CommService.SmsServiceSoap {
        
        public SmsServiceSoapClient() {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RestService.CommService.MessageStateInfo GetMessageState(string sessionID, string messageID) {
            return base.Channel.GetMessageState(sessionID, messageID);
        }
        
        public System.Threading.Tasks.Task<RestService.CommService.MessageStateInfo> GetMessageStateAsync(string sessionID, string messageID) {
            return base.Channel.GetMessageStateAsync(sessionID, messageID);
        }
        
        public string GetSessionID(string login, string password) {
            return base.Channel.GetSessionID(login, password);
        }
        
        public System.Threading.Tasks.Task<string> GetSessionIDAsync(string login, string password) {
            return base.Channel.GetSessionIDAsync(login, password);
        }
        
        public string[] SendMessage(string sessionID, RestService.CommService.Message message) {
            return base.Channel.SendMessage(sessionID, message);
        }
        
        public System.Threading.Tasks.Task<string[]> SendMessageAsync(string sessionID, RestService.CommService.Message message) {
            return base.Channel.SendMessageAsync(sessionID, message);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestService.CommService.SendMessageByTimeZoneResponse RestService.CommService.SmsServiceSoap.SendMessageByTimeZone(RestService.CommService.SendMessageByTimeZoneRequest request) {
            return base.Channel.SendMessageByTimeZone(request);
        }
        
        public string[] SendMessageByTimeZone(string sessionID, string sourceAddress, string destinationAddress, string data, System.DateTime sendDate, System.Nullable<int> validity) {
            RestService.CommService.SendMessageByTimeZoneRequest inValue = new RestService.CommService.SendMessageByTimeZoneRequest();
            inValue.sessionID = sessionID;
            inValue.sourceAddress = sourceAddress;
            inValue.destinationAddress = destinationAddress;
            inValue.data = data;
            inValue.sendDate = sendDate;
            inValue.validity = validity;
            RestService.CommService.SendMessageByTimeZoneResponse retVal = ((RestService.CommService.SmsServiceSoap)(this)).SendMessageByTimeZone(inValue);
            return retVal.SendMessageByTimeZoneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestService.CommService.SendMessageByTimeZoneResponse> RestService.CommService.SmsServiceSoap.SendMessageByTimeZoneAsync(RestService.CommService.SendMessageByTimeZoneRequest request) {
            return base.Channel.SendMessageByTimeZoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestService.CommService.SendMessageByTimeZoneResponse> SendMessageByTimeZoneAsync(string sessionID, string sourceAddress, string destinationAddress, string data, System.DateTime sendDate, System.Nullable<int> validity) {
            RestService.CommService.SendMessageByTimeZoneRequest inValue = new RestService.CommService.SendMessageByTimeZoneRequest();
            inValue.sessionID = sessionID;
            inValue.sourceAddress = sourceAddress;
            inValue.destinationAddress = destinationAddress;
            inValue.data = data;
            inValue.sendDate = sendDate;
            inValue.validity = validity;
            return ((RestService.CommService.SmsServiceSoap)(this)).SendMessageByTimeZoneAsync(inValue);
        }
        
        public decimal GetBalance(string sessionID) {
            return base.Channel.GetBalance(sessionID);
        }
        
        public System.Threading.Tasks.Task<decimal> GetBalanceAsync(string sessionID) {
            return base.Channel.GetBalanceAsync(sessionID);
        }
        
        public RestService.CommService.IncomingMessage[] GetIncomingMessages(string sessionID, System.DateTime maxDateUTC, System.DateTime minDateUTC) {
            return base.Channel.GetIncomingMessages(sessionID, maxDateUTC, minDateUTC);
        }
        
        public System.Threading.Tasks.Task<RestService.CommService.IncomingMessage[]> GetIncomingMessagesAsync(string sessionID, System.DateTime maxDateUTC, System.DateTime minDateUTC) {
            return base.Channel.GetIncomingMessagesAsync(sessionID, maxDateUTC, minDateUTC);
        }
        
        public RestService.CommService.DeliveryStatistics GetStatistics(string sessionId, System.DateTime startDateTime, System.DateTime endDateTime) {
            return base.Channel.GetStatistics(sessionId, startDateTime, endDateTime);
        }
        
        public System.Threading.Tasks.Task<RestService.CommService.DeliveryStatistics> GetStatisticsAsync(string sessionId, System.DateTime startDateTime, System.DateTime endDateTime) {
            return base.Channel.GetStatisticsAsync(sessionId, startDateTime, endDateTime);
        }
    }
}
